### ISSUE TITLE
How to resolve this ?

### ISSUE THREAD

**Issue by hakxcore** [zricethezav/h1domains#7]
$ python3 hackerone.py
raivo
Traceback (most recent call last):
  File "/$PATH/hackerone.py", line 71, in <module>
    targets = hackerone_to_list()
  File "$PATH/hackerone.py", line 56, in hackerone_to_list
    for e in scope_resp['data']['team']['structured_scopes']['edges']:
KeyError: 'data'

**Comment by molitona** [comment]
UP !
